### ISSUE TITLE
.editorconfig file?

### ISSUE THREAD

**Issue by ghost** [1Hyena/cryptograffiti#27]
It'd be good to have a .editorconfig file for things like trailing whitespace, tab size etc. I ran into this problem when I was writing some code and the default config on my editor removed a bunch of trailing whitespace. http://editorconfig.org/

**Comment by 1Hyena** [comment]
trailing whitespaces might be annoying but since they don't change the program behaviour they are not much of a problem. IDEs typically remove trailing whitespaces or at least have an option to do that. If some of the files in cryptograffiti has trailing whitespaces that annoy you then feel free to remove them and make a pull request ;)

BTW, I don't use automated code formatters because I often align code vertically. Automated code formatting would just destroy my custom formatting.

**Comment by ghost** [comment]
Awesome - thanks
